---
- name: Download opentofu archive file in /tmp dir
  ansible.builtin.get_url:
    url: "{{ opentofu_download_baseurl }}/{{ opentofu_archive_filename }}"
    dest: "/tmp/{{ opentofu_archive_filename }}"
    mode: 0755

- name: Verify checksum for opentofu archive file
  when: should_verify_opentofu_checksum
  block:
    - name: Download opentofu archive file checksum in /tmp dir
      ansible.builtin.get_url:
        url: "{{ opentofu_download_baseurl }}/{{ opentofu_sha256sum_filename }}"
        dest: "/tmp/{{ opentofu_sha256sum_filename }}"
        mode: 0755

    - name: Generate checksum file for verification
      ansible.builtin.shell: cd /tmp && sha256sum "{{ opentofu_archive_filename }}" > "{{ opentofu_generated_sha256sum_filename }}"
      changed_when: false

    - name: Verify checksum file
      ansible.builtin.shell: "cd /tmp && sha256sum -c {{ opentofu_generated_sha256sum_filename }}"
      register: opentofu_checksum_result
      changed_when: false

    - name: Check if opentofu archive file checksum is correct
      ansible.builtin.assert:
        that:
          - opentofu_checksum_result.rc == 0
        fail_msg: "the opentofu archive checksum is not correct"

- name: Create opentofu unarchived dir in /tmp
  ansible.builtin.file:
    path: "/tmp/{{ opentofu_archive_filename.split('.tar.gz')[0] }}"
    state: directory
    mode: 0755

- name: Unarchive opentofu archive file
  ansible.builtin.unarchive:
    src: "/tmp/{{ opentofu_archive_filename }}"
    dest: "/tmp/{{ opentofu_archive_filename.split('.tar.gz')[0] }}"
    remote_src: true
    mode: 0755

- name: Copy opentofu binary file to bin dir
  ansible.builtin.copy:
    src: "/tmp/{{ opentofu_archive_filename.split('.tar.gz')[0] }}/tofu"
    dest: "{{ opentofu_bin_dir }}/tofu"
    mode: 0755
    remote_src: true

- name: Find files and directories in /tmp starting with tofu
  ansible.builtin.find:
    paths: "/tmp"
    patterns: "^tofu.*"
    use_regex: true
    file_type: any
  register: opentofu_installation_items
  notify: Cleanup all opentofu installation items
  changed_when: true
